### PR TITLE
Fix shader code to work on macOS

### PR DESCRIPTION
**Pull request by adamhutchings**

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
```
/home/jake/Repos/sniper/src/graphics/shader.cpp:36:1: error: no declaration matches ‘gl::Shader::Shader(ZStringView, ZStringView)’
   36 | Shader::Shader(ZStringView vertex_fname, ZStringView fragment_fname) {
      | ^~~~~~
In file included from /home/jake/Repos/sniper/src/graphics/shader.cpp:1:
/home/jake/Repos/sniper/src/graphics/shader.hpp:22:7: note: candidates are: ‘gl::Shader::Shader(const gl::Shader&)’
   22 | class Shader {
      |       ^~~~~~
/home/jake/Repos/sniper/src/graphics/shader.hpp:37:3: note:                 ‘gl::Shader::Shader(FileContents, FileContents)’
   37 |   Shader(FileContents vertex_source, FileContents fragment_source);
      |   ^~~~~~
/home/jake/Repos/sniper/src/graphics/shader.hpp:22:7: note: ‘class gl::Shader’ defined here
   22 | class Shader {
      |       ^~~~~~
make[2]: *** [CMakeFiles/sniper.dir/build.make:146: CMakeFiles/sniper.dir/src/graphics/shader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/sniper.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by JakeRoggenbuck** [comment]
Build error

**Comment by adamhutchings** [comment]
Alright, will fix.

**Comment by JakeRoggenbuck** [comment]
```
/home/jake/Repos/sniper/src/graphics/shader.cpp: In constructor ‘gl::Shader::Shader(FileContents, FileContents)’:
/home/jake/Repos/sniper/src/graphics/shader.cpp:39:67: error: cannot convert ‘FileContents’ {aka ‘std::basic_string_view<char>’} to ‘ZStringView’ {aka ‘const char*’}
   39 |     std::vector<unsigned char> vertex_source = load_file_as_bytes(vertex_fname);
      |                                                                   ^~~~~~~~~~~~
      |                                                                   |
      |                                                                   FileContents {aka std::basic_string_view<char>}
In file included from /home/jake/Repos/sniper/src/graphics/shader.cpp:8:
/home/jake/Repos/sniper/src/system/file.hpp:33:71: note:   initializing argument 1 of ‘LoadResult<std::vector<unsigned char> > load_file_as_bytes(ZStringView)’
   33 | LoadResult<std::vector<unsigned char>> load_file_as_bytes(ZStringView filename);
      |                                                           ~~~~~~~~~~~~^~~~~~~~
/home/jake/Repos/sniper/src/graphics/shader.cpp:40:69: error: cannot convert ‘FileContents’ {aka ‘std::basic_string_view<char>’} to ‘ZStringView’ {aka ‘const char*’}
   40 |     std::vector<unsigned char> fragment_source = load_file_as_bytes(fragment_fname);
      |                                                                     ^~~~~~~~~~~~~~
      |                                                                     |
      |                                                                     FileContents {aka std::basic_string_view<char>}
/home/jake/Repos/sniper/src/system/file.hpp:33:71: note:   initializing argument 1 of ‘LoadResult<std::vector<unsigned char> > load_file_as_bytes(ZStringView)’
   33 | LoadResult<std::vector<unsigned char>> load_file_as_bytes(ZStringView filename);
      |                                                           ~~~~~~~~~~~~^~~~~~~~
/home/jake/Repos/sniper/src/graphics/shader.cpp:49:33: error: cannot convert ‘std::vector<unsigned char>’ to ‘FileContents’ {aka ‘std::basic_string_view<char>’}
   49 |     int vert = create_subshader(vertex_source, GL_VERTEX_SHADER);
      |                                 ^~~~~~~~~~~~~
      |                                 |
      |                                 std::vector<unsigned char>
In file included from /home/jake/Repos/sniper/src/graphics/shader.cpp:1:
/home/jake/Repos/sniper/src/graphics/shader.hpp:28:39: note:   initializing argument 1 of ‘int gl::Shader::create_subshader(FileContents, GLenum)’
   28 |     int create_subshader(FileContents source, GLenum type);
      |                          ~~~~~~~~~~~~~^~~~~~
/home/jake/Repos/sniper/src/graphics/shader.cpp:50:33: error: cannot convert ‘std::vector<unsigned char>’ to ‘FileContents’ {aka ‘std::basic_string_view<char>’}
   50 |     int frag = create_subshader(fragment_source, GL_FRAGMENT_SHADER);
      |                                 ^~~~~~~~~~~~~~~
      |                                 |
      |                                 std::vector<unsigned char>
/home/jake/Repos/sniper/src/graphics/shader.hpp:28:39: note:   initializing argument 1 of ‘int gl::Shader::create_subshader(FileContents, GLenum)’
   28 |     int create_subshader(FileContents source, GLenum type);
      |                          ~~~~~~~~~~~~~^~~~~~
make[2]: *** [CMakeFiles/sniper.dir/build.make:146: CMakeFiles/sniper.dir/src/graphics/shader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/sniper.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Review by JakeRoggenbuck — APPROVED** [review]
Works! this was before wasd right?

**Pull request merged**
